name: AaronBare
favicon: null
layout_spectrum: 0.03255289723165333
typography_spectrum: 0.9747313458938152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.997945350361988
  lightness: 0.6305485300254077
  saturation: 0.11631579045206308
  rhythmicContrast: 0.3712177586276084
purpose: []
